name: Fly Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} # BẮT BUỘC
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check token presence
        run: 'test -n "$FLY_API_TOKEN" && echo "FLY_API_TOKEN is set" || (echo "missing token" && exit 1)'

      - name: Deploy app
        run: flyctl deploy --remote-only -c fly.toml
        working-directory: .
